#####
###  DOCKER COMPOSE
#
---
- debug:
    msg: START DOCKER COMPOSE...

- name: copy files local to remote with a template (docker-compose)
  template:
    src: docker-compose
    dest: ./docker-compose.yml
  register: result
- name: debug [copy files local to remote with a template (docker-compose)]
  debug:
    var: result

- debug:
    msg: END DOCKER COMPOSE...
