#####
###  DOCKER NGINX
#
---
- debug:
    msg: START DOCKER NGINX...

- name: create folder ./nginx/conf/
  file:
    path: ./nginx/conf/
    state: directory
  register: result
- name: debug [create folder ./nginx/conf/]
  debug:
    var: result

- name: check if certificate exists
  become: true
  shell: 'docker compose run nginx test -e /etc/nginx/ssl/live/{{DOMAIN_NAME}}/fullchain.pem && echo 1 || echo 0'
  # if "0" certificate does not exist, if "1" certificate exists
  register: hasAValidCertificate
- name: debug [check if certificate exists]
  debug:
    var: hasAValidCertificate

- name: copy files local to remote with a template (couchdbHttpCreateCert)
  template:
    src: couchdbHttpCreateCert
    dest: ./nginx/conf/couchdbHttpCreateCert.conf
  register: result
  # if "0" certificate does not exist, we need to create a certificate config
  when: hasAValidCertificate.stdout == "0"
- name: debug [copy files local to remote with a template (couchdbHttpCreateCert)]
  debug:
    var: result

- name: start couchdb, nginx, and certbot with docker-compose up
  become: true
  shell: 'docker compose -f ./docker-compose.yml up --build --detach'
  register: result
- name: debug [start couchdb, nginx, and certbot with docker-compose up]
  debug:
    var: result

- name: reload nginx config
  become: true
  shell: 'docker compose exec nginx nginx -s reload'
  register: result
  # if "0" certificate does not exist, we need to create a certificate config
  when: hasAValidCertificate.stdout == "0"
- name: debug [reload nginx config]
  debug:
    var: result

- debug:
    msg: END DOCKER NGINX...
