#####
###  DOCKER COUCHDB
#
---
- debug:
    msg: START DOCKER COUCHDB...

- name: create folder ./couchdb/conf/
  file:
    path: ./couchdb/conf/local.d
    state: directory
  register: result
- name: debug [create folder ./couchdb/conf/]
  debug:
    var: result

- name: copy files local to remote with a template (Dockerfile)
  template:
    src: Dockerfile
    dest: ./Dockerfile
  register: result
- name: debug [copy files local to remote with a template (Dockerfile)]
  debug:
    var: result

- name: copy files local to remote with a template (local-ini)
  template:
    src: local-ini
    dest: ./couchdb/conf/local.ini
  register: result
- name: debug [copy files local to remote with a template (local-ini)]
  debug:
    var: result

- name: copy files local to remote with a template (local-d-ini)
  template:
    src: local-d-ini
    dest: ./couchdb/conf/local.d/docker.ini
  register: result
- name: debug [copy files local to remote with a template (local-d-ini)]
  debug:
    var: result

- debug:
    msg: END DOCKER COUCHDB...